### ISSUE TITLE
how to rescan a folder when first loop ends

### ISSUE THREAD

**Issue by pieter-groeneweg** [goatface/mplall#1]
Hi,

I just installed this on a RPi4 with omxplayer and it still works!
I did change alsa to HDMI though..

In line 31 it says "forever" which is ok, but...
I am not that into bash scripts (NOOB I am) but how would I stop at the end of a playlist, rescan the folder and start playing the changed series?

case is that folder is changing as new movies may be added (and old ones removed) on auto sync from an outside location. I would like to have the folder rescanned after one series without having to stop and restart...

Probably a very simple thingy...

**Comment by goatface** [comment]
Thanks for your interest in my script!  Nice to know it is still working on the latest systems.

I made two updates aimed to resolve your issues:

1) Very close to the top of the script, I have a new variable where you could set 'hdmi' rather than 'alsa'.

2) The omxplayer playlist now finalizes its loop with an abstracted playlist creation.

Please give the new version a whirl and let me know if these modifications were helpful.

If you have some further suggestions, please do not hesitate to open a new issue or contact me.

Thanks!

**Comment by pieter-groeneweg** [comment]
Thanks this works! Great job!q
Apparently OM player loads the entire piece of movie into memory (swap? I don't know) so even when a file is deleted from the queue it doesn't break any.

New queue is now in the playlist.

There is now one thing I did not have before.. between movies there is a glitch now and I do see the desktop flash before a new movie starts... is this something that can be avoided?

Thanks!

**Comment by goatface** [comment]
try the -b 

options:
   **-b           : black background outside video on RPi omxplayer**

If not, we can discuss Xfce tricks atop Raspbian.  With a small effort, it can all be almost completely black all the time!

**Comment by pieter-groeneweg** [comment]
yes I was running this with the -b.
new day, clean boot.. I have teh glitch in the old script too.. I may have done things yesterday while experimenting that solved it.
running this on top of a LXDE gui by the way. And a GUI is required for my even NOOBer than I am family members ;)
and the NextCloud app that appears to only run in GUI mode..

**Comment by goatface** [comment]
Indeed.  Still, you can install some Xfce tools from apt-get atop LXDE, they are in apt.  Here are some examples below.

Try the xfce4-terminal because it has many more options than the default one in LXDE.  It will be under System Tools after installation.

Once you open it, under View, untick Show Toolbar.  Then unclick Show Menubar (you can right-click to get it back).  Then press F11, now it's full screen black terminal.  If you then don't use the -b option, all you will see at the top is the mplall info (depending the size of the video), and it will "flash" more naturally between tracks.  

Of course, your family members might get confused with this, but F11 is not too hard to remember.  The OSD for mplall is also helpful for people to know how to control it.

I also have a bindkey in .zshrc (should work the same in bash): bindkey -s "\e[15~" "mplall\n"

That is for F5, and then you can get mplall with one keystroke in terminal.  If you want a different keybind, go into vi in Insert mode, press Ctrl+v (not paste) and press the key of interest, and the reference encoding will be typed.

Another advantage of this setup (not using -b) is you can get OSD for the Volume Controls.

Install xfce4-notifyd and xfce4-volumed, add xfce4-volumed to user startup in:

~/.config/lxsession/LXDE-pi/autostart

There might be one or two other things needed, but this is also quite nice.  Again as before, it could be obscured by omxplayer's video, depending if it is full screen or wide screen and the size of your monitor / TV.  

With all that together, here's what it looks like.  Sorry, it is really tricky to screencap so many bells and whistles, so I just took a picture.

![shot0514](https://user-images.githubusercontent.com/1185574/99065914-0a231b00-25a0-11eb-92c3-1155bb49cf9a.png)

**Comment by goatface** [comment]
Here was another trick I tried to avoid glitches with a blackout.  However I never managed to hack it enough so that it worked...

It's using imagemagick (that is what to install to get 'convert' command) to make a 1x1 black pixel and then the simple image viewer feh to full screen the black.  Unfortunately, as you see from these comments, feh was then eating the I/O for mplall/omxplayer and I never figured a way around it, but if you get bored....or you want me to try again, let me know.  It's some pretty obscure hacking attempt :)

#an attempt to show external volume OSD with blackout (not -b)
#feh gui catches the keyboard inputs, though ... 
#CANVAS=/tmp/.mplall_canvas.gif
#convert -size 1x1 canvas:black $CANVAS
#feh -F $CANVAS &

**Comment by pieter-groeneweg** [comment]
Great I will see what I can find.
Meanwhile my attempt was to black a workspace.. (panels to hide and transparent, background to black and no icons in workspace)
Then run the script without a terminal.. created a launcher on the top panel... only thing now is I have no keyboard controls anymore...
Not your controls from the script (cannot ctrl c and q) nor the short keys in omplayer...

I cannot even escape from it anymore.. though VNC access shows me the normal desktop... 
Unless I add start with  terminal enabled.

Maybe it is the same issue as with your experiment, it looks like omxplayer is running in an instance without a window.. 
I may eplain this a little odd.. sorry for that.. not my first language..

**Comment by goatface** [comment]
Running without a terminal will be a bad idea.  I was thinking about this today, reflecting on your comments.  I considered to suggest it, but I realized quickly you'd have to use pgrep and kill (probably by ssh since you cannot see anything).  Or reboot.  Oops! 

I am considering an idea along these lines with adding a Zenity "ok" popup with an option.  However, I fear one might encounter these same basic issues and it would not allow one to control the media player.  It was an idea I was thinking about for your issue, but I think this too would not work so well.

omxplayer is very odd.  Even if you were to launch it from another machine by ssh -Y it's going to play through the RPi hardware screen.  However, if it was not so odd, there would be no reason for such a shell script I suppose....

**Comment by goatface** [comment]
Also I was thinking ...

The RPi2 default energy savings in Raspbian will blackout the screen after say 5 minutes.  omxplayer will continue to be shown.

Maybe when you said you did not see these glitches, you were not touching the keyboard for awhile.

**Comment by pieter-groeneweg** [comment]
i think I found some solution.. minify the terminal window to the panel..
I installed wmctrl

 wmctrl -k on minimizes to tray if user then clicks the terminal in the tray, it is available for controls again.

I put it around 159 just above "OSD"

There is only one glitch left..after the first movie... I may have to choose a better line but my experience in bash is too little.. learning as we speak (write)
wmctrl is nice as it will close anything..
I could even create a separate blacked workspace and leave the rest as is..on workspace just for this...

But yes your thought may be right indeed...... see if I can change this desktop time out

**Comment by pieter-groeneweg** [comment]
oh bummer.. it only helps me when i VNC.. :(

back to the drawing board.. maybe only have the terminal active when the video plays (and is hidden behind the player anyway)

**Comment by goatface** [comment]
Yeah, black desktop with the terminal in the middle of the screen and not touching anything definitely works!

In my profile, you can see my personal email address to discuss more.

I worry to 'close' or 'resolve' this discussion, since it is nice.   However, at least for the initial Issue directly related to my script I believe I Resolved?

These discussions are very useful for me, as you see I am telling things here which are not on the README.  It will be nice in the future since I may be able to consolidate very specific suggestions or styles, etc.

Thanks!

**Comment by pieter-groeneweg** [comment]
Will I open a new issue for this so possible other users can chip in their two cents?

**Comment by goatface** [comment]
Yes please!  You may call it something about the 'blackout' screen or similar.  It would also help searches and other users with that title.  

We can discuss further.  Once you open that issue, I will be comfortable to close this issue and move our present discussion to that thread.  

Thanks!
