### ISSUE TITLE
about the 'blackout' screen

### ISSUE THREAD

**Issue by pieter-groeneweg** [goatface/mplall#2]
for some history, see: https://github.com/goatface/mplall/issues/1

on short:
in between movies in the playlist, the desktop shows for a blink of a second.. This is when staring with terminal.
I can start without terminal but then all control is lost and not to be regained.

my short term solution is:
hide panels
set background to black
minify the terminal (and all else) by adding wmctrl -k to the script just above OSD around line 164 works after second change of movies

```
	  while read -u 10 entry; do
	    wmctrl -k on
	    OSD 
	    echo -e "\e[34;1mPlaying \e[93;1m$entry \e[34;1m. . .\e[0m\n"
	    "$MPLAYER" $OPTIONS "$entry" 
	  done 10< "$PLAYLIST"
```

There maybe a much better position in the code .. I am just starting to get to learn some bash

It at least brings back some control.
Alt TAB then ctrl+c to stop.

It would be very nice to have some way to control it without the need of an active terminal and/or have the player use a window instead of the bare output (hope I am explaining this correct) 
And for some use that sprung to mind.. use buttons on GPIO pins to trigger next (q) and exit (ctrl+c)...

Or is this going beyond bash?

**Comment by goatface** [comment]
My understanding of the history is the omxplayer was a command-line playground for the developers of the engine.

This is actually the people who made Kodi.  It can also use the accelerated hardware of the RPi to play videos.  Of course in this case, you have to make your own playlists, and I have no idea how to 're-scan' or other things.  However it has a gorgeous GUI, and it probably is not this goofy command-line interface run by my shell script, if you know what I mean...

I have a couple ideas how we may work on the point from a shell script perspective (and I like my script!), but depending on your application, there are actually GUIs out there, programmed by professionals, using this engine.

**Comment by pieter-groeneweg** [comment]
Even though it is mentioned that omxplayer is deprecated and the makers advise VLC
It it the accelerated hardware of the player I want to use.. any other player on a PI I know sort of <<beeps>>.
The omxplayer is the only one I know that plays video without stuttering. Even on lesser Pi than Pi4. VLC is advised but the play back quality is still lowsy.

When I just run it without a Desktop environment I cannot solve the glitch at all. With desktop I can at least "black" it in a workaround.

I need to check with the GUI's out there on this player then.. I don't need complex controls... just volume up/down and next.. and of course "quit" and preferrably with key strokes.

**Comment by goatface** [comment]
I also heard this sad news.  I agree VLC was recommended but it is lousy.  It can't play DVDs very well, and it cannot accelerate the graphics.  

Okay, I will look into the issue.  Glad you like the script and let's see if I can come up with some new hacks.  :)

**Comment by goatface** [comment]
I finally had a chance to attack this problem.  There are two new options, -M to minimize the terminal, and -B to make our own Blackout.

To utilize all of these, you will need: feh, imagemagick, xdotool, and wmctrl.  These are all in apt-get for Raspian.  I apologize for the many required dependencies to accomplish these tricks.

Now, even `mplall -B` will still flash the terminal, because in this mode we retain keyboard control over the media playback.  The terminal also needs to be placed close to the vertical center of the screen, and relatively narrow, otherwise you will see it behind the video.

If you don't want to see this, you can use -M to minimize the terminal, but then you lose control of the media until you refocus to the terminal.

Note that because my new Blackout mode uses the simple image viewer feh, the hotkey to quit is q, which is also a hotkey used in omxplayer, so a novice might be able to guess this.  It could come up in combined -MB mode because the full screen black pixel might prevent you from seeing / accessing the control panel to unminimize the Terminal.  Pressing Alt+Tab once will also bring the Terminal back as well.

Hopefully, you were still interested in these features.  -B should prevent you from requiring an all black desktop, for example.

Note that I cannot think of a way to retain control of the media player and never see the Terminal flash between tracks.  The only way would be like a frameless black terminal with black background and black text saved as terminal profile ... which sounds pretty awful :)

**Comment by pieter-groeneweg** [comment]
Hi, indeed I am sitll interested but was (and still am) a bit occupied by work.. covid keeps me busy.

But I may find some spare time next week to see it working.

Tx,
